"""Render ``00_project_overview.md`` from a :class:`ProjectInventory`.

This file is generated output, never hand-edited (see PLAN.md section 53).
It states what was *observed* and marks anything uncertain.
"""

from __future__ import annotations

from code_memory.models.inventory import FileKind, ProjectInventory

_KIND_LABELS = {
    FileKind.JAVA_MAIN: "Java (main)",
    FileKind.JAVA_TEST: "Java (test)",
    FileKind.SCALA: "Scala",
    FileKind.RESOURCE: "Main resources",
    FileKind.TEST_RESOURCE: "Test resources",
    FileKind.MAVEN_POM: "Maven POM",
    FileKind.GRADLE_BUILD: "Gradle build script",
    FileKind.GRADLE_SETTINGS: "Gradle settings",
    FileKind.GRADLE_PROPERTIES: "Gradle properties",
    FileKind.APP_CONFIG: "App configuration",
    FileKind.SPARK_CONFIG: "Spark configuration",
    FileKind.SQL: "SQL files",
    FileKind.DOCKER: "Docker files",
    FileKind.README: "README",
    FileKind.DOC: "Documentation",
    FileKind.SCRIPT: "Scripts",
    FileKind.BUILD_OTHER: "Other config",
    FileKind.OTHER: "Other",
}


def _fmt(value: str | None) -> str:
    return value if value else "_unknown_"


def render_overview(inv: ProjectInventory) -> str:
    b = inv.build
    counts = inv.counts_by_kind()
    lines: list[str] = []
    add = lines.append

    add("# 00 - Project Overview")
    add("")
    add("> Generated by Local Code Memory (Phase 1 inventory). Do not edit by hand.")
    add(f"> Scan `{inv.scan_id}` - scanner v{inv.scanner_version} - {inv.generated_at}")
    add("")

    add("## Repository")
    add("")
    add(f"- Root: `{inv.project_root}`")
    add(f"- Git branch: `{_fmt(inv.git_branch)}`")
    add(f"- Git commit: `{_fmt(inv.git_commit)}`")
    add(f"- Files inventoried: **{len(inv.files)}**")
    add(f"- Java LOC (approx): **{inv.total_java_loc()}**")
    add("")

    add("## Build & Frameworks (observed)")
    add("")
    add(f"- Build system: **{b.build_system}**")
    add(f"- Coordinates: `{_fmt(b.group_id)}:{_fmt(b.artifact_id)}:{_fmt(b.version)}`")
    add(f"- Java version: **{_fmt(b.java_version)}**")
    add(f"- Spring Boot version: **{_fmt(b.spring_boot_version)}**")
    add(f"- Spark version: **{_fmt(b.spark_version)}**")
    add(f"- Scala version: **{_fmt(b.scala_version)}**")
    add(f"- Database drivers: {_join(b.database_drivers)}")
    add(f"- Logging frameworks: {_join(b.logging_frameworks)}")
    add(f"- Testing frameworks: {_join(b.testing_frameworks)}")
    add(f"- Declared dependencies: **{len(b.dependencies)}**")
    add("")

    style = _infer_style(b, counts)
    add("## Inferred application style")
    add("")
    add(f"- {style}")
    add("")
    add("_Inference only - confirm against source. Phase 4/5 refine this._")
    add("")

    add("## File inventory by kind")
    add("")
    add("| Kind | Count |")
    add("| --- | ---: |")
    for kind, count in counts.items():
        label = _KIND_LABELS.get(FileKind(kind), kind)
        add(f"| {label} | {count} |")
    add("")

    if b.dependencies:
        add("## Dependencies")
        add("")
        add("| Group | Artifact | Version |")
        add("| --- | --- | --- |")
        for dep in b.dependencies:
            add(f"| {dep['group']} | {dep['artifact']} | {dep['version'] or '_?_'} |")
        add("")

    if inv.warnings:
        add("## Scan warnings")
        add("")
        for w in inv.warnings:
            add(f"- {w}")
        add("")

    return "\n".join(lines) + "\n"


def _join(items: list[str]) -> str:
    return ", ".join(f"`{i}`" for i in items) if items else "_none detected_"


def _infer_style(b, counts: dict[str, int]) -> str:
    has_spark = bool(b.spark_version) or counts.get("spark_config", 0) > 0
    has_spring = bool(b.spring_boot_version)
    if has_spark and has_spring:
        return "Mixed: Spring Boot service **and** Spark/ETL code present."
    if has_spark:
        return "Java + Apache Spark / ETL job."
    if has_spring:
        return "Java + Spring Boot service (likely REST/SQL)."
    return "Plain Java backend - framework not detected from build files."
