"""Phase 10 - generate the complete Markdown context pack.

Every file is derived from the graph + metadata on each scan; none is a
second source of truth (PLAN.md §53). Missing inputs produce an honest
"not detected / not available" section rather than a guess.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from code_memory import SCANNER_VERSION, SCHEMA_VERSION, __version__
from code_memory.config import Config
from code_memory.context.util import scan_config_properties, scan_logging
from code_memory.graph.memory_repository import InMemoryGraphRepository
from code_memory.logging_setup import get_logger
from code_memory.models.inventory import FileKind

log = get_logger("context.generator")


@dataclass
class _Ctx:
    config: Config
    java: Any            # JavaScanResult
    inventory: Any       # ProjectInventory
    scan_id: str
    repo: InMemoryGraphRepository
    out: Path


def generate_context_pack(config: Config, java_result, inventory,
                          scan_id: str) -> list[Path]:
    graph = java_result.graph
    out = config.output_dir
    ctx_dir = out / "context"
    ctx_dir.mkdir(parents=True, exist_ok=True)

    c = _Ctx(config, java_result, inventory, scan_id,
             InMemoryGraphRepository(graph=graph), out)

    files: dict[str, str] = {
        "00_project_overview.md": _f00(c),
        "01_architecture.md": _f01(c),
        "02_modules.md": _f02(c),
        "03_dependencies.md": _f03(c),
        "04_configuration.md": _f04(c),
        "05_database.md": _f05(c),
        "06_api_endpoints.md": _reuse_api(c),
        "07_call_graph.md": _reuse_callgraph(c),
        "08_data_flow.md": _f08(c),
        "09_exception_flow.md": _f09(c),
        "10_logging.md": _f10(c),
        "11_tests.md": _f11(c),
        "12_spark.md": _reuse_spark(c),
        "13_sql.md": _reuse_sql(c),
        "14_ai_coding_instructions.md": _f14(c),
    }

    written: list[Path] = []
    for name, body in files.items():
        if body is None:
            continue
        p = ctx_dir / name
        p.write_text(body, encoding="utf-8")
        written.append(p)

    quality = out / "reports" / "quality_report.md"
    quality.parent.mkdir(parents=True, exist_ok=True)
    quality.write_text(_quality_report(c), encoding="utf-8")
    written.append(quality)

    manifest = out / "manifest.json"
    manifest.write_text(json.dumps(_manifest(c, written), indent=2) + "\n",
                        encoding="utf-8")
    written.append(manifest)

    log.info("context pack generated", extra={"files": len(written)})
    return written


# -- header helper -----------------------------------------------------
def _hdr(title: str, c: _Ctx, note: str = "") -> list[str]:
    return [
        f"# {title}", "",
        f"> Generated by Local Code Memory {__version__} - scan `{c.scan_id}` - "
        f"{datetime.now(timezone.utc).isoformat()}",
        f"> {note}" if note else "> Do not edit by hand; regenerated on every scan.",
        "",
    ]


def _short(node_id: str) -> str:
    return node_id.split(":", 1)[-1]


# -- 00 project overview ---------------------------------------------
def _f00(c: _Ctx) -> str:
    from code_memory.scanner.overview import render_overview
    base = render_overview(c.inventory).rstrip()
    g = c.repo.stats()
    extra = [
        "", "## Code memory", "",
        f"- Graph: **{g['nodes']}** nodes / **{g['edges']}** edges",
        f"- Node kinds: {g['nodes_by_kind']}",
    ]
    if c.java.spring and c.java.spring.is_spring():
        extra.append(f"- Spring: {c.java.spring.counts()}")
    if c.java.sql and c.java.sql.is_present():
        extra.append(f"- SQL: {c.java.sql.counts()}")
    if c.java.spark and c.java.spark.detected:
        extra.append(f"- Spark: {c.java.spark.counts()}")
    return base + "\n" + "\n".join(extra) + "\n"


# -- 01 architecture ----------------------------------------------
_LAYER_RULES = [
    ("Controller/API", ("RestController", "Controller"),
     ("controller", "web", "rest", "api", "resource", "endpoint")),
    ("Service", ("Service",), ("service", "svc", "usecase", "application")),
    ("Repository/DAO", ("Repository",),
     ("repository", "repo", "dao", "persistence", "store", "mapper")),
    ("Configuration", ("Configuration",), ("config", "configuration")),
    ("ETL/Spark", (), ("etl", "job", "spark", "pipeline", "batch")),
    ("Domain/Model", (), ("domain", "model", "entity", "dto", "dbo", "vo", "pojo")),
    ("Integration", (), ("client", "gateway", "integration", "external", "adapter")),
    ("Utility", (), ("util", "utils", "helper", "common", "support")),
]


def _f01(c: _Ctx) -> str:
    types = c.repo.find_nodes(kind="Class") + c.repo.find_nodes(kind="Interface")
    buckets: dict[str, list[str]] = {name: [] for name, _, _ in _LAYER_RULES}
    unknown: list[str] = []
    for t in types:
        fqn = t.get("fqn", t["id"])
        stereo = t.get("spring_stereotype")
        pkg = (t.get("package") or "").lower()
        placed = False
        for name, stereos, hints in _LAYER_RULES:
            if (stereo and stereo in stereos) or any(h in pkg for h in hints) \
                    or (name == "ETL/Spark" and t.get("spark_job")):
                buckets[name].append(fqn)
                placed = True
                break
        if not placed:
            unknown.append(fqn)

    lines = _hdr("01 - Architecture (inferred)", c,
                 "Layers inferred from Spring stereotypes + package names. "
                 "Observed vs inferred vs unknown are kept distinct.")
    for name, _, _ in _LAYER_RULES:
        members = sorted(buckets[name])
        if not members:
            continue
        conf = "observed" if any(
            c.repo.get_node(f"type:{m}") and
            c.repo.get_node(f"type:{m}").get("spring_stereotype")
            for m in members) else "inferred"
        lines.append(f"## {name}  _(confidence: {conf})_")
        lines += [f"- `{m}`" for m in members[:60]]
        lines.append("")
    if unknown:
        lines.append("## Unclassified _(unknown)_")
        lines += [f"- `{m}`" for m in sorted(unknown)[:60]]
        lines.append("")
    return "\n".join(lines) + "\n"


# -- 02 modules ----------------------------------------------
def _f02(c: _Ctx) -> str:
    pkgs = c.repo.find_nodes(kind="Package")
    lines = _hdr("02 - Modules & packages", c)
    lines += ["| Package | Files | Types |", "| --- | ---: | ---: |"]
    for p in sorted(pkgs, key=lambda n: n["name"]):
        files = c.repo.neighbors(p["id"], edge_types=("CONTAINS",), direction="out")
        types = sum(len(c.repo.neighbors(f["id"], edge_types=("DECLARES",),
                                         direction="out")) for f in files)
        lines.append(f"| `{p['name']}` | {len(files)} | {types} |")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 03 dependencies ------------------------------------------
def _f03(c: _Ctx) -> str:
    b = c.inventory.build
    lines = _hdr("03 - Dependencies", c)
    lines += [f"- Build system: **{b.build_system}**",
              f"- Java: {b.java_version or '?'}  Spring Boot: "
              f"{b.spring_boot_version or '-'}  Spark: {b.spark_version or '-'}",
              ""]
    if b.dependencies:
        lines += ["| Group | Artifact | Version |", "| --- | --- | --- |"]
        for d in b.dependencies:
            lines.append(f"| {d['group']} | {d['artifact']} | {d['version'] or '?'} |")
    else:
        lines.append("_No declared dependencies parsed._")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 04 configuration ----------------------------------------
def _f04(c: _Ctx) -> str:
    rels = [e.relative_path for e in c.inventory.files
            if e.kind in (FileKind.APP_CONFIG, FileKind.SPARK_CONFIG)]
    markers = c.config.get("security.secret_markers")
    rows = (scan_config_properties(c.config.project_root, rels, tuple(markers))
            if markers else
            scan_config_properties(c.config.project_root, rels))
    lines = _hdr("04 - Configuration", c,
                 "Property keys from application.* / spark configs. Secret "
                 "values are redacted; secrets are never written to context.")
    if not rows:
        lines.append("_No application configuration files found._")
        return "\n".join(lines) + "\n"
    lines += ["| File | Key | Value |", "| --- | --- | --- |"]
    for r in rows[:400]:
        lines.append(f"| `{r['file']}` | `{r['key']}` | "
                     f"{'`' + str(r['value']) + '`' if not r['secret'] else '_redacted_'} |")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 05 database -------------------------------------------
def _f05(c: _Ctx) -> str:
    lines = _hdr("05 - Database", c)
    tables = c.repo.find_nodes(kind="Table")
    if not tables:
        lines.append("_No SQL / tables detected._")
        return "\n".join(lines) + "\n"
    drivers = c.inventory.build.database_drivers
    lines.append(f"- Drivers (from build): {', '.join(drivers) or '-'}")
    lines.append(f"- Tables: **{len(tables)}**")
    lines.append("")
    lines += ["| Table | Read by (methods) | Written by (methods) |",
              "| --- | --- | --- |"]
    for t in sorted(tables, key=lambda n: n["name"]):
        usage = c.repo.find_database_usage(t["name"])
        lines.append(
            f"| `{t['name']}` "
            f"| {', '.join(_short(m) for m in usage['read_by'][:5]) or '-'} "
            f"| {', '.join(_short(m) for m in usage['written_by'][:5]) or '-'} |")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 08 data flow -----------------------------------------
def _f08(c: _Ctx) -> str:
    lines = _hdr("08 - Data flow", c,
                 "Endpoint request flows, Spark pipelines, and standalone "
                 "(batch/ETL/CLI) entrypoints, from CALLS + table edges.")
    endpoints = c.repo.find_nodes(kind="Endpoint")
    if endpoints:
        lines += ["## HTTP request flows", ""]
        for ep in sorted(endpoints, key=lambda n: n["name"]):
            flow = c.repo.find_endpoint_flow(ep["id"])
            chain = " -> ".join(_short(s["id"]) for s in flow["flow"][:8])
            lines.append(f"- **{ep['name']}** -> `{_short(flow['handler'] or '?')}`"
                         + (f" -> {chain}" if chain else ""))
        lines.append("")
    if c.java.spark and c.java.spark.is_present():
        lines += ["## Spark pipelines", ""]
        for job in c.java.spark.jobs:
            lines.append(f"- `{job.method_fqn}`: "
                         f"{', '.join(job.reads_tables) or job.paths or '?'} "
                         f"--[{', '.join(job.transformations[:6])}]--> "
                         f"{', '.join(job.writes_tables) or '?'}")
        lines.append("")

    # Neither a Spring endpoint nor a Spark job (e.g. a plain ETL job with a
    # main()/run() driver) still has its call chain in the graph - just no
    # dedicated view until now. Surface up to 5 candidates, ranked by name
    # (main/run/execute/...) then by fan-out.
    entrypoints = c.repo.find_entrypoints()
    if entrypoints:
        lines += ["## Standalone entrypoints (batch / ETL / CLI)", "",
                  "_Detected as: nothing in this scan calls them, and they call "
                  "something else. Not annotation-based - works for plain Java too._",
                  ""]
        for ep in entrypoints[:5]:
            flow = c.repo.find_call_flow(ep["id"], max_depth=6)
            chain = " -> ".join(_short(s["id"]) for s in flow[:10])
            lines.append(f"- `{ep['fqn']}`" + (f" -> {chain}" if chain else ""))
        if len(entrypoints) > 5:
            lines.append(f"- _(+{len(entrypoints) - 5} more - see `graph` / "
                         f"`impact` for any of them)_")
        lines.append("")

    if len(lines) <= 6:
        lines.append("_No endpoint, Spark, or standalone entrypoint flows detected._")
    return "\n".join(lines) + "\n"


# -- 09 exception flow -----------------------------------
def _f09(c: _Ctx) -> str:
    lines = _hdr("09 - Exception flow", c)
    thrown: dict[str, list[str]] = {}
    caught: dict[str, list[str]] = {}
    for e in c.repo._edges:
        if e["type"] == "THROWS":
            thrown.setdefault(_short(e["dst"]), []).append(_short(e["src"]))
        elif e["type"] == "CATCHES":
            caught.setdefault(_short(e["dst"]), []).append(_short(e["src"]))
    handlers = [n for n in c.repo.find_nodes() if n.get("exception_handler")]

    if thrown:
        lines += ["## Thrown", "", "| Exception | Declared by |",
                  "| --- | --- |"]
        for exc, ms in sorted(thrown.items()):
            lines.append(f"| `{exc}` | {', '.join(sorted(set(ms))[:6])} |")
        lines.append("")
    if caught:
        lines += ["## Caught", "", "| Exception | Caught in |", "| --- | --- |"]
        for exc, ms in sorted(caught.items()):
            lines.append(f"| `{exc}` | {', '.join(sorted(set(ms))[:6])} |")
        lines.append("")
    if handlers:
        lines += ["## @ExceptionHandler methods", ""]
        for h in handlers:
            tgt = [nb["id"] for nb in c.repo.neighbors(h["id"],
                                                       edge_types=("HANDLES",))]
            lines.append(f"- `{h.get('fqn', h['id'])}` handles "
                         f"{', '.join(_short(t) for t in tgt) or '?'}")
        lines.append("")
    if len(lines) <= 6:
        lines.append("_No throws / catches / handlers detected._")
    return "\n".join(lines) + "\n"


# -- 10 logging ------------------------------------------
def _f10(c: _Ctx) -> str:
    info = scan_logging(c.java.parsed_files)
    lines = _hdr("10 - Logging", c,
                 "Heuristic: logger.<level>() calls recognised from the call "
                 "graph. Missing logging is a candidate, not a defect.")
    lines += [
        f"- Logging calls by level: {info['by_level'] or '-'}",
        f"- Methods with logging: {len(info['logged_methods'])} / "
        f"{info['method_total']}",
        "",
        "## Candidates for added logging",
        "",
        "_Endpoints, @Transactional, DB ops, exception paths, `throws` methods "
        "that currently log nothing._",
        "",
    ]
    for fqn in info["candidates_without_logging"]:
        lines.append(f"- `{fqn}`")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 11 tests -------------------------------------------
def _f11(c: _Ctx) -> str:
    lines = _hdr("11 - Tests", c,
                 "Test classes are those in a test source tree or named *Test / "
                 "*IT. Coverage below is call-reachability, not a real report.")
    test_files = [e.relative_path for e in c.inventory.files
                  if e.kind == FileKind.JAVA_TEST]
    test_methods = [n for n in c.repo.find_nodes(kind="Method")
                    if "Test" in (n.get("owner") or "")
                    or "test" in (n.get("owner") or "").lower()]
    prod_methods = [n for n in c.repo.find_nodes(kind="Method")
                    if n not in test_methods and "Test" not in (n.get("owner") or "")]

    covered = set()
    for tm in test_methods:
        for callee in c.repo.find_impact(tm["id"])["callees"]:
            covered.add(callee)
    prod_ids = {n["id"] for n in prod_methods}
    covered &= prod_ids
    uncovered = sorted(prod_ids - covered)

    lines += [
        f"- Test files: {len(test_files)}   Test methods: {len(test_methods)}",
        f"- Production methods reachable from a test: "
        f"{len(covered)} / {len(prod_ids)}",
        "",
        "## Production methods with no reachable test", "",
    ]
    for mid in uncovered[:80]:
        lines.append(f"- `{_short(mid)}`")
    lines.append("")
    return "\n".join(lines) + "\n"


# -- 14 AI coding instructions ---------------------------
def _f14(c: _Ctx) -> str:
    b = c.inventory.build
    g = c.repo.stats()
    spring = c.java.spring
    endpoints = c.repo.find_nodes(kind="Endpoint")
    entry_hint = [n["fqn"] for n in c.repo.find_nodes(kind="Method")
                  if n.get("name") == "main"]

    lines = [
        "# 14 - AI Coding Instructions", "",
        "> The instruction layer of this Code Memory. Give this file (plus a "
        "task-specific pack from `code-memory context`) to a local coding LLM.",
        "",
        "## Repository", "",
        f"- Build: **{b.build_system}**, Java {b.java_version or '?'}",
        f"- Frameworks: "
        f"{'Spring Boot ' + b.spring_boot_version if b.spring_boot_version else ''}"
        f"{'  Spark ' + b.spark_version if b.spark_version else ''}".strip() or "plain Java",
        f"- Database drivers: {', '.join(b.database_drivers) or 'none detected'}",
        f"- Graph: {g['nodes']} nodes, {g['edges']} edges "
        f"({g['nodes_by_kind']})",
        f"- HTTP endpoints: {len(endpoints)}",
        f"- Known entrypoints: {', '.join(entry_hint) or '-'}",
        "",
        "## Architecture", "",
        "See `01_architecture.md`. Layers were inferred - respect the existing "
        "structure; do not introduce a new layering.",
        "",
    ]
    if spring and spring.is_spring():
        lines += [
            "## Spring conventions", "",
            "- Controllers delegate to services; services use repositories.",
            "- Constructor injection is used for dependencies (see `INJECTS` edges).",
            "- Follow existing `@RequestMapping` path style.",
            "",
        ]
    lines += [
        "## When modifying code", "",
        "1. Inspect the target method (`code-memory graph <symbol>`).",
        "2. Inspect its callers and callees (`code-memory impact <symbol>`).",
        "3. Inspect related tests (`11_tests.md`).",
        "4. Inspect configuration it reads (`04_configuration.md`).",
        "5. Inspect SQL / tables it touches (`05_database.md`, `13_sql.md`).",
        "6. Preserve the existing architecture and naming.",
        "7. Keep the change minimal; avoid unrelated edits.",
        "8. Update or add tests.",
        "9. Report exact file:line ranges for every change.",
        "",
        "## Trust rules", "",
        "- Edges carry a confidence tag (HIGH/MEDIUM/LOW/UNKNOWN). "
        "Never treat MEDIUM/LOW/UNKNOWN as confirmed.",
        "- The source code is the ground truth; this memory is a generated index.",
        "",
    ]
    return "\n".join(lines) + "\n"


# -- reuse java_scan renderers ---------------------------
def _reuse_api(c: _Ctx):
    if not (c.java.spring and c.java.spring.is_spring()):
        return None
    from code_memory.scanner.java_scan import _render_api_endpoints
    return _render_api_endpoints(c.java.graph, c.java.spring)


def _reuse_callgraph(c: _Ctx):
    from code_memory.scanner.java_scan import _render_call_graph
    return _render_call_graph(c.java.graph)


def _reuse_spark(c: _Ctx):
    if not (c.java.spark and c.java.spark.is_present()):
        return None
    from code_memory.scanner.java_scan import _render_spark
    return _render_spark(c.java.spark)


def _reuse_sql(c: _Ctx):
    if not (c.java.sql and c.java.sql.is_present()):
        return None
    from code_memory.scanner.java_scan import _render_sql
    return _render_sql(c.java.graph, c.java.sql)


# -- quality report + manifest ---------------------------
def _quality_report(c: _Ctx) -> str:
    g = c.repo.stats()
    gc = c.java.graph.counts()
    ps = c.java.status_counts
    total = sum(ps.values()) or 1
    lines = _hdr("Quality report", c,
                 "Measured, not claimed. These are extraction metrics, not a "
                 "statement that the system 'understands' the code.")
    lines += [
        "| Metric | Value |", "| --- | ---: |",
        f"| Java files parsed | {sum(ps.values())} |",
        f"| Parse success rate | {ps.get('success', 0) / total:.1%} |",
        f"| Graph nodes | {g['nodes']} |",
        f"| Graph edges | {g['edges']} |",
        f"| Unresolved symbols | {gc.get('unresolved_count', 0)} |",
        f"| CALLS edges | {gc.get('call_edges', 0)} |",
        f"| Call resolution rate | {gc.get('call_resolution_rate')} |",
    ]
    if c.java.sql and c.java.sql.is_present():
        sc = c.java.sql.counts()
        lines.append(f"| SQL statements / parsed cleanly | "
                     f"{sc['sql_statements']} / {sc['sql_parsed_ok']} |")
    if getattr(c.java, "vector", None):
        pass
    lines.append("")
    return "\n".join(lines) + "\n"


def _manifest(c: _Ctx, written: list[Path]) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scan_id": c.scan_id,
        "tool_version": __version__,
        "scanner_version": SCANNER_VERSION,
        "schema_version": SCHEMA_VERSION,
        "git_commit": c.inventory.git_commit,
        "git_branch": c.inventory.git_branch,
        "project_root": str(c.config.project_root),
        "graph": c.repo.stats(),
        "artifacts": [str(p.relative_to(c.out)) for p in written],
    }
