"""LLM provider abstraction + implementations."""

from __future__ import annotations

import abc
import json
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any

from code_memory.config import Config
from code_memory.logging_setup import get_logger

log = get_logger("llm")


@dataclass
class LLMResponse:
    text: str
    model: str
    provider: str
    meta: dict[str, Any]


class LLMProvider(abc.ABC):
    name = "abstract"
    model = ""

    @abc.abstractmethod
    def generate(self, *, system: str, prompt: str,
                 temperature: float = 0.1) -> LLMResponse:
        ...

    def available(self) -> bool:
        return True


class EchoProvider(LLMProvider):
    """Offline provider: returns a well-formed stub so the advisor pipeline and
    its tests run without a model. It does *not* reason - it summarises the
    prompt and emits the required JSON skeleton."""

    name = "echo"

    def __init__(self, model: str = "echo"):
        self.model = model

    def generate(self, *, system, prompt, temperature=0.1) -> LLMResponse:
        if "unified diff" in prompt.lower():
            return LLMResponse(
                "# EchoProvider produced no patch - configure llm.provider: "
                "ollama.\n# (no diff)\n", self.model, self.name,
                {"offline": True})
        task = ""
        for line in prompt.splitlines():
            if line.strip().startswith(("> ", "Task:")):
                task = line.strip().lstrip("> ").removeprefix("Task:").strip()
                break
        stub = {
            "summary": f"(offline echo) no model configured; task was: {task}"[:200],
            "confidence": "LOW",
            "files_to_change": [],
            "files_to_review": [],
            "tests_to_update": [],
            "risks": ["Generated by EchoProvider - configure llm.provider: ollama "
                      "for a real answer."],
            "implementation_plan": [
                "Set llm.provider: ollama and pull a coding model.",
                "Re-run `code-memory context \"<task>\" --ask`.",
            ],
        }
        return LLMResponse(json.dumps(stub, indent=2) +
                           "\n\n_EchoProvider: configure a local model for real analysis._",
                           self.model, self.name, {"offline": True})


class OllamaProvider(LLMProvider):
    name = "ollama"

    def __init__(self, base_url: str, model: str, context_window: int = 32768):
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.context_window = context_window

    def available(self) -> bool:
        try:
            with urllib.request.urlopen(f"{self.base_url}/api/tags", timeout=3):
                return True
        except Exception:
            return False

    def generate(self, *, system, prompt, temperature=0.1) -> LLMResponse:
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            "stream": False,
            "options": {"temperature": temperature,
                        "num_ctx": self.context_window},
        }
        req = urllib.request.Request(
            f"{self.base_url}/api/chat",
            data=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(req, timeout=600) as resp:
                data = json.loads(resp.read())
        except (urllib.error.URLError, TimeoutError) as exc:
            raise RuntimeError(f"Ollama request failed: {exc}") from exc
        return LLMResponse(
            data.get("message", {}).get("content", ""),
            self.model, self.name,
            {"eval_count": data.get("eval_count"),
             "prompt_eval_count": data.get("prompt_eval_count"),
             "total_duration_ms": (data.get("total_duration") or 0) // 1_000_000},
        )


def get_llm_provider(config: Config) -> LLMProvider:
    provider = str(config.get("llm.provider", "ollama")).lower()
    model = config.get("llm.model", "qwen3-coder:30b")
    if provider == "ollama":
        p = OllamaProvider(config.get("llm.base_url", "http://localhost:11434"),
                           model, int(config.get("llm.context_window", 32768)))
        if p.available():
            return p
        log.warning("ollama unavailable, using offline EchoProvider")
    return EchoProvider(model)
